name: GitHub action with HTML Preview

on: 
  pull_request:

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: HTML Preview
        uses: pavi2410/html-preview-action@v4
        id: html_preview
        with:
          html_file: 'ankidroid.html'
          job_summary: true
