name: Add Comment with HTML Preview

on: 
  pull_request:

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: HTML Preview
        uses: pavi2410/html-preview-action@v4
        id: html_preview
        with:
          html_file: 'ankidroid.html'
          job_summary: true
      - uses: actions/github-script@v7
        env:
          url: ${{ steps.html_preview.outputs.url }}
        with:
          script: |
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: `[Preview this commit](${process.env.url})`
              })
